### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by leadagency**
Hi Jared

I'm Andrew from The Lead Agency. We look after the digital marketing for the PSC Group (that your father was acquired by). We have been requested to make several contact and compliance changes. Can you please deploy these and arrange to transfer the Git ownership over to us. My email address is: andrew@leadagency.com.au if you need to check that this isn't a random person trying to make changes!

### CODE REVIEW

**Comment by Jamchiller** [comment]
Hey Andrew! Thanks for the message and no problem - I've merged your PR and will look into transferring over the ownership now 👍

**Comment by Jamchiller** [comment]
I've had a look and Github won't let me transfer ownership to @leadagency because you 'leadagency already has a repository in the brokerman network'. I think this means you'll have to delete your fork first, and then I'll be able to transfer. 

Let me know once you do so and I'll transfer!

**Comment by leadagency** [comment]
Thanks Jared, that’s done.

I hate deleting in GitHub, but it looks like you should be able to transfer it over to us now.




The Lead Agency
______________________________
w. www.leadagency.com.au
***@***.***
a. Level 1, 195 Swan Street Richmond VIC 3121

**Comment by Jamchiller** [comment]
No problem - I've now made a transfer request. Let me know if you have any more questions, happy to help 👍 

Jared

**Pull request merged**
